import { COMPARISONS } from '@/features/compare/comparison-data'

export const SITEMAP_STATIC_PATHS = [
  '/',
  '/about',
  '/developers',
  '/image-cdn-cost-calculator',
  '/pricing',
  '/learn',
  '/blog',
  '/blog/ar',
  '/authors/raed-bahri',
  '/compare',
  ...Object.keys(COMPARISONS).map((slug) => `/compare/${slug}`),
  '/self-hosted-image-cdn',
  '/methodology/comparisons',
  '/security',
  '/status',
  '/support',
  '/changelog',
  '/legal/terms',
  '/legal/privacy',
  '/legal/dpa',
  '/legal/license',
]
