/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123llmFileChar125DottxtRouteImport } from './routes/{$llmFile}[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalLicenseRouteImport } from './routes/legal/license'
import { Route as LegalDpaRouteImport } from './routes/legal/dpa'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as ImgSplatRouteImport } from './routes/img/$'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppOperationsIndexRouteImport } from './routes/app/operations/index'
import { Route as AppLogsIndexRouteImport } from './routes/app/logs/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/app/analytics/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as OgDocsSplatRouteImport } from './routes/og/docs/$'
import { Route as ApiSdkSplatRouteImport } from './routes/api/sdk/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiInternalLogsStreamRouteImport } from './routes/api/internal/logs/stream'
import { Route as ApiInternalBillingReportUsageRouteImport } from './routes/api/internal/billing/report-usage'

const Char123llmFileChar125DottxtRoute =
  Char123llmFileChar125DottxtRouteImport.update({
    id: '/{$llmFile}.txt',
    path: '/{$llmFile}.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalLicenseRoute = LegalLicenseRouteImport.update({
  id: '/legal/license',
  path: '/legal/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDpaRoute = LegalDpaRouteImport.update({
  id: '/legal/dpa',
  path: '/legal/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgSplatRoute = ImgSplatRouteImport.update({
  id: '/img/$',
  path: '/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOperationsIndexRoute = AppOperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogsIndexRoute = AppLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const OgDocsSplatRoute = OgDocsSplatRouteImport.update({
  id: '/og/docs/$',
  path: '/og/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSdkSplatRoute = ApiSdkSplatRouteImport.update({
  id: '/api/sdk/$',
  path: '/api/sdk/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalLogsStreamRoute = ApiInternalLogsStreamRouteImport.update({
  id: '/api/internal/logs/stream',
  path: '/api/internal/logs/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalBillingReportUsageRoute =
  ApiInternalBillingReportUsageRouteImport.update({
    id: '/api/internal/billing/report-usage',
    path: '/api/internal/billing/report-usage',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$llmFile}.txt': typeof Char123llmFileChar125DottxtRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/img/$': typeof ImgSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sdk/$': typeof ApiSdkSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/logs/': typeof AppLogsIndexRoute
  '/app/operations/': typeof AppOperationsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/api/internal/billing/report-usage': typeof ApiInternalBillingReportUsageRoute
  '/api/internal/logs/stream': typeof ApiInternalLogsStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$llmFile}.txt': typeof Char123llmFileChar125DottxtRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/img/$': typeof ImgSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sdk/$': typeof ApiSdkSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/analytics': typeof AppAnalyticsIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/logs': typeof AppLogsIndexRoute
  '/app/operations': typeof AppOperationsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/api/internal/billing/report-usage': typeof ApiInternalBillingReportUsageRoute
  '/api/internal/logs/stream': typeof ApiInternalLogsStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$llmFile}.txt': typeof Char123llmFileChar125DottxtRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/img/$': typeof ImgSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sdk/$': typeof ApiSdkSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/logs/': typeof AppLogsIndexRoute
  '/app/operations/': typeof AppOperationsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/api/internal/billing/report-usage': typeof ApiInternalBillingReportUsageRoute
  '/api/internal/logs/stream': typeof ApiInternalLogsStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/accept-invite'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{$llmFile}.txt'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/api/health'
    | '/api/search'
    | '/blog/$'
    | '/docs/$'
    | '/img/$'
    | '/invite/$token'
    | '/legal/dpa'
    | '/legal/license'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/blog/'
    | '/api/auth/$'
    | '/api/sdk/$'
    | '/og/docs/$'
    | '/app/account/'
    | '/app/admin/'
    | '/app/analytics/'
    | '/app/dashboard/'
    | '/app/logs/'
    | '/app/operations/'
    | '/app/settings/'
    | '/api/internal/billing/report-usage'
    | '/api/internal/logs/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{$llmFile}.txt'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/api/health'
    | '/api/search'
    | '/blog/$'
    | '/docs/$'
    | '/img/$'
    | '/invite/$token'
    | '/legal/dpa'
    | '/legal/license'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app'
    | '/blog'
    | '/api/auth/$'
    | '/api/sdk/$'
    | '/og/docs/$'
    | '/app/account'
    | '/app/admin'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/logs'
    | '/app/operations'
    | '/app/settings'
    | '/api/internal/billing/report-usage'
    | '/api/internal/logs/stream'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/accept-invite'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{$llmFile}.txt'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/api/health'
    | '/api/search'
    | '/blog/$'
    | '/docs/$'
    | '/img/$'
    | '/invite/$token'
    | '/legal/dpa'
    | '/legal/license'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/blog/'
    | '/api/auth/$'
    | '/api/sdk/$'
    | '/og/docs/$'
    | '/app/account/'
    | '/app/admin/'
    | '/app/analytics/'
    | '/app/dashboard/'
    | '/app/logs/'
    | '/app/operations/'
    | '/app/settings/'
    | '/api/internal/billing/report-usage'
    | '/api/internal/logs/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123llmFileChar125DottxtRoute: typeof Char123llmFileChar125DottxtRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogSplatRoute: typeof BlogSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ImgSplatRoute: typeof ImgSplatRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LegalDpaRoute: typeof LegalDpaRoute
  LegalLicenseRoute: typeof LegalLicenseRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSdkSplatRoute: typeof ApiSdkSplatRoute
  OgDocsSplatRoute: typeof OgDocsSplatRoute
  ApiInternalBillingReportUsageRoute: typeof ApiInternalBillingReportUsageRoute
  ApiInternalLogsStreamRoute: typeof ApiInternalLogsStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{$llmFile}.txt': {
      id: '/{$llmFile}.txt'
      path: '/{$llmFile}.txt'
      fullPath: '/{$llmFile}.txt'
      preLoaderRoute: typeof Char123llmFileChar125DottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/license': {
      id: '/legal/license'
      path: '/legal/license'
      fullPath: '/legal/license'
      preLoaderRoute: typeof LegalLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dpa': {
      id: '/legal/dpa'
      path: '/legal/dpa'
      fullPath: '/legal/dpa'
      preLoaderRoute: typeof LegalDpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$': {
      id: '/img/$'
      path: '/img/$'
      fullPath: '/img/$'
      preLoaderRoute: typeof ImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/operations/': {
      id: '/app/operations/'
      path: '/operations'
      fullPath: '/app/operations/'
      preLoaderRoute: typeof AppOperationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/logs/': {
      id: '/app/logs/'
      path: '/logs'
      fullPath: '/app/logs/'
      preLoaderRoute: typeof AppLogsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics/': {
      id: '/app/analytics/'
      path: '/analytics'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/account'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/og/docs/$': {
      id: '/og/docs/$'
      path: '/og/docs/$'
      fullPath: '/og/docs/$'
      preLoaderRoute: typeof OgDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sdk/$': {
      id: '/api/sdk/$'
      path: '/api/sdk/$'
      fullPath: '/api/sdk/$'
      preLoaderRoute: typeof ApiSdkSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/logs/stream': {
      id: '/api/internal/logs/stream'
      path: '/api/internal/logs/stream'
      fullPath: '/api/internal/logs/stream'
      preLoaderRoute: typeof ApiInternalLogsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/billing/report-usage': {
      id: '/api/internal/billing/report-usage'
      path: '/api/internal/billing/report-usage'
      fullPath: '/api/internal/billing/report-usage'
      preLoaderRoute: typeof ApiInternalBillingReportUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppLogsIndexRoute: typeof AppLogsIndexRoute
  AppOperationsIndexRoute: typeof AppOperationsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppLogsIndexRoute: AppLogsIndexRoute,
  AppOperationsIndexRoute: AppOperationsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123llmFileChar125DottxtRoute: Char123llmFileChar125DottxtRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogSplatRoute: BlogSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  ImgSplatRoute: ImgSplatRoute,
  InviteTokenRoute: InviteTokenRoute,
  LegalDpaRoute: LegalDpaRoute,
  LegalLicenseRoute: LegalLicenseRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSdkSplatRoute: ApiSdkSplatRoute,
  OgDocsSplatRoute: OgDocsSplatRoute,
  ApiInternalBillingReportUsageRoute: ApiInternalBillingReportUsageRoute,
  ApiInternalLogsStreamRoute: ApiInternalLogsStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
