/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123llmFileChar125DottxtRouteImport } from './routes/{$llmFile}[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiKeenpixRouteImport } from './routes/api/keenpix'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppLogsIndexRouteImport } from './routes/app/logs/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/app/analytics/index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as OgDocsSplatRouteImport } from './routes/og/docs/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const Char123llmFileChar125DottxtRoute =
  Char123llmFileChar125DottxtRouteImport.update({
    id: '/{$llmFile}.txt',
    path: '/{$llmFile}.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeenpixRoute = ApiKeenpixRouteImport.update({
  id: '/api/keenpix',
  path: '/api/keenpix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogsIndexRoute = AppLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const OgDocsSplatRoute = OgDocsSplatRouteImport.update({
  id: '/og/docs/$',
  path: '/og/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$llmFile}.txt': typeof Char123llmFileChar125DottxtRoute
  '/login': typeof authLoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/keenpix': typeof ApiKeenpixRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/logs/': typeof AppLogsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$llmFile}.txt': typeof Char123llmFileChar125DottxtRoute
  '/login': typeof authLoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/keenpix': typeof ApiKeenpixRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/analytics': typeof AppAnalyticsIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/logs': typeof AppLogsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$llmFile}.txt': typeof Char123llmFileChar125DottxtRoute
  '/(auth)/login': typeof authLoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/keenpix': typeof ApiKeenpixRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/logs/': typeof AppLogsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{$llmFile}.txt'
    | '/login'
    | '/api/health'
    | '/api/keenpix'
    | '/api/search'
    | '/docs/$'
    | '/app/'
    | '/api/auth/$'
    | '/og/docs/$'
    | '/app/account/'
    | '/app/analytics/'
    | '/app/dashboard/'
    | '/app/logs/'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{$llmFile}.txt'
    | '/login'
    | '/api/health'
    | '/api/keenpix'
    | '/api/search'
    | '/docs/$'
    | '/app'
    | '/api/auth/$'
    | '/og/docs/$'
    | '/app/account'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/logs'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{$llmFile}.txt'
    | '/(auth)/login'
    | '/api/health'
    | '/api/keenpix'
    | '/api/search'
    | '/docs/$'
    | '/app/'
    | '/api/auth/$'
    | '/og/docs/$'
    | '/app/account/'
    | '/app/analytics/'
    | '/app/dashboard/'
    | '/app/logs/'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123llmFileChar125DottxtRoute: typeof Char123llmFileChar125DottxtRoute
  authLoginRoute: typeof authLoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiKeenpixRoute: typeof ApiKeenpixRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OgDocsSplatRoute: typeof OgDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{$llmFile}.txt': {
      id: '/{$llmFile}.txt'
      path: '/{$llmFile}.txt'
      fullPath: '/{$llmFile}.txt'
      preLoaderRoute: typeof Char123llmFileChar125DottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keenpix': {
      id: '/api/keenpix'
      path: '/api/keenpix'
      fullPath: '/api/keenpix'
      preLoaderRoute: typeof ApiKeenpixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/logs/': {
      id: '/app/logs/'
      path: '/logs'
      fullPath: '/app/logs/'
      preLoaderRoute: typeof AppLogsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics/': {
      id: '/app/analytics/'
      path: '/analytics'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/account'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/og/docs/$': {
      id: '/og/docs/$'
      path: '/og/docs/$'
      fullPath: '/og/docs/$'
      preLoaderRoute: typeof OgDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppLogsIndexRoute: typeof AppLogsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppLogsIndexRoute: AppLogsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123llmFileChar125DottxtRoute: Char123llmFileChar125DottxtRoute,
  authLoginRoute: authLoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiKeenpixRoute: ApiKeenpixRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OgDocsSplatRoute: OgDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
